version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sql-server;Database=FamilyAppDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true;
    depends_on:
      - sql-server
    restart: unless-stopped

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlvolume:
